### ISSUE TITLE
Is there a cyg-wrapper that performs the opposite functionality?

### ISSUE THREAD

**Issue by jordwalke** [LucHermitte/Bash-scripts#4]
Is there something like cyg-wrapper that allows invoking cygwin programs from windows command shells?

**Comment by LucHermitte** [comment]
Hi.
Not that I'm aware of. 
Beside, I'm not sure this is necessary. Indeed, programs compiled for cygwin are usually able to decode pathnames expressed in windows form.
Do you have a precise example that I could play with?

**Comment by jordwalke** [comment]
I had just assumed there would be many issues, but glad to hear that most cygwin programs normalize paths.
